// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS3-UXBXvjGUMHDDJeYXBCnbwjw8MCyrk',
    appId: '1:508006163827:web:d6412b224d71f9665f9106',
    messagingSenderId: '508006163827',
    projectId: 'foodshop-f0828',
    authDomain: 'foodshop-f0828.firebaseapp.com',
    storageBucket: 'foodshop-f0828.appspot.com',
    measurementId: 'G-L3Y814R0VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCErA82xbL79Z2m00j2N2LNVq2eZng6908',
    appId: '1:508006163827:android:ff7e5bcb989f165b5f9106',
    messagingSenderId: '508006163827',
    projectId: 'foodshop-f0828',
    storageBucket: 'foodshop-f0828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpMYcPKNX5v1s8fS0rd6PjYlJliyCehc',
    appId: '1:508006163827:ios:4594d8225ffd20385f9106',
    messagingSenderId: '508006163827',
    projectId: 'foodshop-f0828',
    storageBucket: 'foodshop-f0828.appspot.com',
    iosBundleId: 'com.example.findFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPpMYcPKNX5v1s8fS0rd6PjYlJliyCehc',
    appId: '1:508006163827:ios:4594d8225ffd20385f9106',
    messagingSenderId: '508006163827',
    projectId: 'foodshop-f0828',
    storageBucket: 'foodshop-f0828.appspot.com',
    iosBundleId: 'com.example.findFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS3-UXBXvjGUMHDDJeYXBCnbwjw8MCyrk',
    appId: '1:508006163827:web:1575097c812d79025f9106',
    messagingSenderId: '508006163827',
    projectId: 'foodshop-f0828',
    authDomain: 'foodshop-f0828.firebaseapp.com',
    storageBucket: 'foodshop-f0828.appspot.com',
    measurementId: 'G-TSJMC3EF5S',
  );
}
